package dsw.rudok.app.core.errhandler;

public enum EventType {
    CANNOT_ADD_CHILD_TO_LEAF, NAME_CANNOT_BE_EMPTY_STRING,
    CANNOT_NAME_NODE_WITH_EXISTING_NAME,
    NEED_TO_SELECT_PROJECT,
    CONCEPT_MUST_HAVE_NAME,
    NEED_TO_SELECT_STATE,
    NEED_TO_SELECT_ELEMENT,
    NEED_TO_SELECT_AT_LEAST_ONE_ELEMENT,
    LINE_MUST_HAVE_START_POINT,
    LINE_MUST_HAVE_END_POINT,
    YOU_GO_OUTSIDE_WORKSPACE,
    LINK_CANNOT_BE_INSIDE_ONE_ELEMENT,
    NEED_TO_PRESS_LEFT_CLICK,
    NEED_TO_SAVE_ONLY_PROJECT,
    PROJECT_ALREADY_EXIST,
    PNG_CREATED, NEED_TO_SAVE_ONLY_MAP,
    CANNOT_ZOOM_BECAUSE_JT_IS_NOT_SHOWING,
    NEED_TO_CLICK_ON_ELEMENT,
    PROJECT_SUCCESIFULL_LOADED,
    NODE_CANNOT_BE_DELETED
}
